[package]
name = "contexide-workflow-profiles"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
async-trait = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
contexide-core = { path = "../contexide-core" }
contexide-workflow-core = { path = "../contexide-workflow-core" }
