[package]
name = "contexide-messaging-nats"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
contexide-core = { path = "../contexide-core" }
contexide-config = { path = "../contexide-config" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
uuid = { workspace = true, features = ["v7"] }
time = { workspace = true, features = ["serde"] }
async-nats = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
futures = { workspace = true }
tokio-stream = { workspace = true }
once_cell = { workspace = true }
anyhow = { workspace = true }
