[package]
name = "contexide-storage-pg"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
contexide-core = { path = "../contexide-core", features = ["db"] }
contexide-workflow-core = { path = "../contexide-workflow-core" }

uuid = { workspace = true }
async-trait = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
